package com.anderhome.prefs.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.anderhome.prefs.model.MemberProfileQuestion;

/**
 * Class _Member was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Member extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BCRYPT_PASSWORD = Property.create("bcryptPassword", String.class);
    public static final Property<String> EMAIL_ADDRESS = Property.create("emailAddress", String.class);
    public static final Property<String> FIRST_NAME = Property.create("firstName", String.class);
    public static final Property<String> LAST_NAME = Property.create("lastName", String.class);
    public static final Property<String> PHONE_NUMBER = Property.create("phoneNumber", String.class);
    public static final Property<byte[]> PHOTO = Property.create("photo", byte[].class);
    public static final Property<Integer> SESSION_TOKEN_HASH = Property.create("sessionTokenHash", Integer.class);
    public static final Property<List<MemberProfileQuestion>> MEMBER_PROFILE_QUESTIONS = Property.create("memberProfileQuestions", List.class);

    public void setBcryptPassword(String bcryptPassword) {
        writeProperty("bcryptPassword", bcryptPassword);
    }
    public String getBcryptPassword() {
        return (String)readProperty("bcryptPassword");
    }

    public void setEmailAddress(String emailAddress) {
        writeProperty("emailAddress", emailAddress);
    }
    public String getEmailAddress() {
        return (String)readProperty("emailAddress");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setPhoneNumber(String phoneNumber) {
        writeProperty("phoneNumber", phoneNumber);
    }
    public String getPhoneNumber() {
        return (String)readProperty("phoneNumber");
    }

    public void setPhoto(byte[] photo) {
        writeProperty("photo", photo);
    }
    public byte[] getPhoto() {
        return (byte[])readProperty("photo");
    }

    public void setSessionTokenHash(Integer sessionTokenHash) {
        writeProperty("sessionTokenHash", sessionTokenHash);
    }
    public Integer getSessionTokenHash() {
        return (Integer)readProperty("sessionTokenHash");
    }

    public void addToMemberProfileQuestions(MemberProfileQuestion obj) {
        addToManyTarget("memberProfileQuestions", obj, true);
    }
    public void removeFromMemberProfileQuestions(MemberProfileQuestion obj) {
        removeToManyTarget("memberProfileQuestions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MemberProfileQuestion> getMemberProfileQuestions() {
        return (List<MemberProfileQuestion>)readProperty("memberProfileQuestions");
    }


}
