package com.anderhome.prefs.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.anderhome.prefs.model.Member;
import com.anderhome.prefs.model.MemberProfileQuestionOption;
import com.anderhome.prefs.model.ProfileQuestion;

/**
 * Class _MemberProfileQuestion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MemberProfileQuestion extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Member> MEMBER = Property.create("member", Member.class);
    public static final Property<List<MemberProfileQuestionOption>> MEMBER_PROFILE_QUESTION_OPTIONS = Property.create("memberProfileQuestionOptions", List.class);
    public static final Property<ProfileQuestion> PROFILE_QUESTION = Property.create("profileQuestion", ProfileQuestion.class);

    public void setMember(Member member) {
        setToOneTarget("member", member, true);
    }

    public Member getMember() {
        return (Member)readProperty("member");
    }


    public void addToMemberProfileQuestionOptions(MemberProfileQuestionOption obj) {
        addToManyTarget("memberProfileQuestionOptions", obj, true);
    }
    public void removeFromMemberProfileQuestionOptions(MemberProfileQuestionOption obj) {
        removeToManyTarget("memberProfileQuestionOptions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MemberProfileQuestionOption> getMemberProfileQuestionOptions() {
        return (List<MemberProfileQuestionOption>)readProperty("memberProfileQuestionOptions");
    }


    public void setProfileQuestion(ProfileQuestion profileQuestion) {
        setToOneTarget("profileQuestion", profileQuestion, true);
    }

    public ProfileQuestion getProfileQuestion() {
        return (ProfileQuestion)readProperty("profileQuestion");
    }


}
