package com.anderhome.prefs.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.anderhome.prefs.model.ProfileQuestion;

/**
 * Class _ProfileQuestionOption was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProfileQuestionOption extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> QUESTION_OPTION = Property.create("questionOption", String.class);
    public static final Property<ProfileQuestion> PROFILE_QUESTION = Property.create("profileQuestion", ProfileQuestion.class);

    public void setQuestionOption(String questionOption) {
        writeProperty("questionOption", questionOption);
    }
    public String getQuestionOption() {
        return (String)readProperty("questionOption");
    }

    public void setProfileQuestion(ProfileQuestion profileQuestion) {
        setToOneTarget("profileQuestion", profileQuestion, true);
    }

    public ProfileQuestion getProfileQuestion() {
        return (ProfileQuestion)readProperty("profileQuestion");
    }


}
