package com.anderhome.prefs.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.anderhome.prefs.model.ProfileQuestionOption;

/**
 * Class _ProfileQuestion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProfileQuestion extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCR = Property.create("descr", String.class);
    public static final Property<Boolean> IS_ACTIVE = Property.create("isActive", Boolean.class);
    public static final Property<Integer> ORDINAL = Property.create("ordinal", Integer.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<List<ProfileQuestionOption>> PROFILE_QUESTION_OPTIONS = Property.create("profileQuestionOptions", List.class);

    public void setDescr(String descr) {
        writeProperty("descr", descr);
    }
    public String getDescr() {
        return (String)readProperty("descr");
    }

    public void setIsActive(boolean isActive) {
        writeProperty("isActive", isActive);
    }
	public boolean isIsActive() {
        Boolean value = (Boolean)readProperty("isActive");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setOrdinal(Integer ordinal) {
        writeProperty("ordinal", ordinal);
    }
    public Integer getOrdinal() {
        return (Integer)readProperty("ordinal");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void addToProfileQuestionOptions(ProfileQuestionOption obj) {
        addToManyTarget("profileQuestionOptions", obj, true);
    }
    public void removeFromProfileQuestionOptions(ProfileQuestionOption obj) {
        removeToManyTarget("profileQuestionOptions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProfileQuestionOption> getProfileQuestionOptions() {
        return (List<ProfileQuestionOption>)readProperty("profileQuestionOptions");
    }


}
